# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VW5_8d4yCj8bc-2_AbnXTysQQN7XFccy
"""

from docx import Document
import re
import os
from google.colab import files

# 📂 저장 폴더
output_dir = "chunked_articles_cl"
os.makedirs(output_dir, exist_ok=True)

# 📄 파일 업로드
uploaded = files.upload()
filename = list(uploaded.keys())[0]
doc = Document(filename)

def paragraph_has_bold(para):
    return any(run.bold for run in para.runs if run.text.strip())

# 삭제 감지: 제목만 기준
삭제제목패턴 = re.compile(r"삭제", re.IGNORECASE)

# 추적용 변수
last_chapter = ""
last_section = ""
article_starts = []

for i, para in enumerate(doc.paragraphs):
    text = para.text.strip()
    if not text:
        continue

    # 장
    m_chap = re.match(r"(제\d+장)\s+(.+)", text)
    if m_chap:
        chapter_title = m_chap.group(2).strip()
        last_chapter = f"{m_chap.group(1)} {chapter_title}"
        continue

    # 절
    m_sect = re.match(r"(제\d+절)\s*\(?([^)]+)?\)?", text)
    if m_sect:
        section_title = (m_sect.group(2) or "").strip()
        last_section = f"{m_sect.group(1)}({section_title})"
        continue

    # 조
    if paragraph_has_bold(para):
        m_article = re.match(r"(제\d+조(?:의\d+)?)(?:\s*\(([^)]+)\)|\s+(.+))?", text)
        if m_article:
            조번호 = m_article.group(1)
            제목 = m_article.group(2) or m_article.group(3) or ""
            article_starts.append((i, last_chapter, last_section, 조번호.strip(), 제목.strip(), text))

# chunking 및 저장
for idx, (para_idx, 장, 절, 조, 제목, 첫문단) in enumerate(article_starts):
    start = para_idx + 1
    end = article_starts[idx + 1][0] if idx + 1 < len(article_starts) else len(doc.paragraphs)
    나머지 = "\n".join(p.text.strip() for p in doc.paragraphs[start:end] if p.text.strip())
    full_text = 첫문단 + "\n" + 나머지

    # 삭제 여부: 제목(장/절/조)에 "삭제" 포함 여부만 기준
    삭제문서 = any([
        삭제제목패턴.search(장),
        삭제제목패턴.search(절),
        삭제제목패턴.search(조),
        삭제제목패턴.search(제목)
    ])
    삭제여부 = "1" if 삭제문서 else "0"
    삭제_suffix = "삭제" if 삭제문서 else ""

    # 파일명
    장_part = 장 if 장 else "미지정장"
    절_part = 절 if 절 else "미지정절"
    조_part = f"{조}({제목})" if 제목 else 조
    파일명 = f"{장_part}_{절_part}_{조_part}_{삭제_suffix}.txt"

    # 저장
    with open(os.path.join(output_dir, 파일명), "w", encoding="utf-8") as f:
        f.write(full_text)

# 압축 및 다운로드
!zip -r chunked_articles_cl.zip chunked_articles_cl > /dev/null
files.download("chunked_articles_cl.zip")